export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const NEW_TWEET = 'NEW_TWEET';
export const NEW_TWEET_CLOSE = 'NEW_TWEET_CLOSE';